[package]
name = "crates_io_stats_dbdump"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.22"
simple-log = "1.6.0"
db-dump = "0.7.4"
chrono = "0.4.38"
csv = "1.3.0"
semver = "1.0.23"
tempdir = "0.3.7"
reqwest = { version = "0.12.5", features = ["blocking"] }
